Добавление графики
htmlacademy-htmlcss/2065035-sedona-35 pull request #3
Opened 2022-10-09 12:29 UTC by Nemchenco96

Картинки с макета выгрузил, прогнал через редакторы для уменьшения занимаемой памяти, подключил. размеры и описание сделал.
Не стал добавлять мелкие элементы для списков и звезды рейтинга для отелей, как я понял, это при подключении стилей потом лучше сделать?

2022-10-10 10:00 UTC, Dima-Dim commented
> Не стал добавлять мелкие элементы для списков и звезды рейтинга для отелей, как я понял, это при подключении стилей потом лучше сделать?

Да, декоративные элементы будут по программе позже.

2022-10-10 10:04 UTC, Dima-Dim requested changes
images/HTML_Academy_logo.svg и подобные - https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-03
[hearts.svg](https://github.com/htmlacademy-htmlcss/2065035-sedona-35/pull/3/files#diff-8c8fa7d19be79e048a283878ef3b07fd3d8ea411e6f23a5b80dcfb053479b470) - как быть если в избранном окажется больше или меньше единиц?

[main_logo1.jpg](https://github.com/htmlacademy-htmlcss/2065035-sedona-35/pull/3/files#diff-4a2af44070813fab0a4d3a364730324d7f679d81b21b06efd2c0d44a2a4bb19c) - что-то как-то очень много всего в этом лого.

2022-10-10 10:04 UTC, Dima-Dim commented on catalog.html
> +      <img class="logo" src="images/logo.svg" width="140" height="70,5" alt="Логотип Sedona"
Нет отступа у вложенного тега.

2022-10-10 10:04 UTC, Dima-Dim commented on catalog.html
> +              <span class="visually-hidden"><img src="images/search.svg" width="20" height="22" alt="Поиск"></span>
Если тег `img` обернуть в тега с классом `visually-hidden`, то изображения не отобразится в том месте, где оно ожидается. Класс `visually-hidden` используется для текста, который нужно доступно скрыть.

2022-10-12 03:55 UTC, Dima-Dim requested changes
Не все замечания из предыдущей проверки исправлены и добавлены новые ошибки.
images/hearts.svg - всё ещё включает в себя цифру.
images/HTML_Academy_logo.svg - https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-03

2022-10-12 03:55 UTC, Dima-Dim commented on catalog.html
> +            <a class="breadcrumbs-link" href="index.html"><img src="images/home_page.svg" weight="12" height="12" alt="На главную"></a>
Здесь тоже декоративное изображение, которые не должно быть в разметке.

2022-10-12 03:55 UTC, Dima-Dim commented on catalog.html
> +            <img src="images/should.svg" weight="6,39" height="9,94" alt="">
А это что за элемент списка появился?

2022-10-12 03:55 UTC, Dima-Dim commented on catalog.html
> +          <span class="visually-hidden"><img src="images/list1.svg" width="48" height="48" alt="Показать рядами"></span>
Изображение внутри тега `visually-hidden` не убед видно? В чём смысл? Ну и это тоже декоративное изображение которое не нужно в разметке.

2022-10-15 04:36 UTC, Dima-Dim requested changes
images/House.svg - https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-03

2022-10-15 04:36 UTC, Dima-Dim commented on catalog.html
> +              <span class="search"> Поиск </span>
Почему `visually-hidden` заменён на `search`?

2022-10-15 04:36 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-item-1">
Про цифры в названиях классов мы с тобой проговорили, надеюсь что ты будешь использовать их только там, где без них действительно никак.

2022-10-15 10:53 UTC, Nemchenco96 commented on catalog.html
> +              <span class="search"> Поиск </span>
Я так понимаю, класс к декоративному элементу мы будем применять непосредственно к ссылке?

2022-10-17 11:05 UTC, Dima-Dim commented on catalog.html
> +              <span class="search"> Поиск </span>
Это вам расскажут в разделе про декоративные элементы.

2022-10-17 11:18 UTC, Dima-Dim commented on styles/styles.css
> +font-family: "PT Sans", sans-serif;
Почему нет отступов?

2022-10-17 11:18 UTC, Dima-Dim commented on styles/styles.css
> +font-family: "PT Sans", sans-serif;
Разве `font-family` не наследуется?

2022-10-17 11:18 UTC, merged

2022-10-17 13:31 UTC, Nemchenco96 commented on styles/styles.css
> +font-family: "PT Sans", sans-serif;
Точно. Шрифт один. Уже исправил

2022-10-17 13:31 UTC, Nemchenco96 commented on styles/styles.css
> +font-family: "PT Sans", sans-serif;
Исправил